name: breadchain_sdk
description: 'A new Flutter package project.'
version: 0.0.1
homepage:

scripts:
  gen-force: 'dart run build_runner build --delete-conflicting-outputs'
  gen: 'dart run build_runner build'

environment:
  sdk: ^3.5.4
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  blurrycontainer: ^2.1.0
  flutter_bloc: ^8.1.6
  syncfusion_flutter_gauges: ^28.1.35
  freezed_annotation: ^2.4.4
  formz: ^0.8.0
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/svgs/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
